services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000" # Web interface (HTTP)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
    environment:
      - TZ=UTC
    networks:
      - portainer_network

volumes:
  portainer_data:
    name: portainer_data

networks:
  portainer_network:
    name: portainer_network
    driver: bridge
